# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0380e9723077fc1c6d0d91bab38c7294e11127618e95a4b3bbf28e9f98aca7e03e1c9fdcc9827bdebec3dec2f3577e5eb54bf38699ec86476b1bbeb2a66a333f

test:
  secret_key_base: 45f2cbd8e56887566bf70640261824eeddf5f29b67dcf2309f51f0a611355e1447db9f83c597dc1a27e459b4a666e6ea64c7980b58506516e6821adde0dc76d4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
